---
title: "About"
---

## History

The National Pastime League (NPL) was founded in February 2015 by Evan Brunell (Defenestrations of Prague) and Gerald Andriole (former owner, MIT Beavers).

The current NPL directors are Jarrett Seidler (Asbury Park Bosses), Tommy Bennett (Los Angeles Bulldog), Chris Fargis (Brooklyn TOOTBLANs), Bret Sayre (Cheesequake Cheddar), Lukas Vlahos (New York Valkyries), and Wes French (Midwest Ducksnorts).

Before founding NPL, Evan and Gerald were members of the Big Show League, part of Reality Fantasy Baseball. Big Show League was in operation for many years, with the most recent iteration born in 2006. Using RFB’s proprietary engine, Big Show was designed to mimic MLB as closely as possible for the most realistic fantasy baseball experience possible.

For several reasons, Evan and Gerald decided to create their own take on a fantasy baseball league modeled after actual mechanics of an MLB team and formed their own league. Many owners from Big Show are also members of NPL.

After one year using RFB’s proprietary engine, NPL shifted to the Scoresheet platform. Using real-life statistics of baseball players, fantasy statistics are generated with head-to-head games against other teams in the league. Adherence to MLB rules is prioritized and applied whenever possible.

## About the Rules

### Introduction

This rules document covers most, but not all, rules in NPL. If rules are missing, owners may request that the rule be added to the document. Rule changes suggestions may be submitted to the NPL Directors, also serving as the Rules Committee (RC) by email at npldirectors@googlegroups.com. For Winter Meeting rule considerations, please submit your proposal at this link.

All rule changes must go through the Rules Committee with the exception of programming or technological developments, which will be announced to the league as rapidly as NPL ambassadors learn of changes.

### Committee

The Rules Committee comprises all [league directors](mailto:npldirectors@gmail.com).

### Rules Changes

#### Standard Rule Changes

All rules must meet the approval of the RC before the league can vote on the rules. For those that do not meet approval from the RC, a vote on the rule will not be considered.

The majority of all rule changes will be voted on and applied in the early offseason, primarily at the Winter Meetings. Most rule changes will fall under this category.

For league votes on rule changes, a quorum (51%) of teams in the league must weigh in, and votes are by simple majority.

#### Emergency Rule Changes

The Rules Committee may propose an Emergency Rule Change at any point to address immediate and pressing situations outside of the Winter Meetings that has significant impact if the rule is instituted. Emergency Rule Change proposals will be voted on in a timely fashion by the league and require 75% approval from voting participants (those who abstain are not counted in the vote) to pass, and a quorum must be reached. Emergency Rule Changes that pass will be expedited and go into immediate effect upon completion of the vote.

#### Executive Rule Changes

The Rules Committee has the power to institute Executive Rule Changes at any point in the season in situations where the committee deems it appropriate. Oftentimes, these rule changes are either transactional in nature, must be altered to meet new MLB CBA rule changes, and/or are “common sense” changes. Executive Rule Changes requires 90% of the league to vote to reverse it, with a quorum met.

## League Fees

League fees of $200 every year for the right to own and operate a team for the following season.

$79 of the league fees go to Scoresheet for game-engine operations, while $20 is designated for the operations fund. The operations fund helps maintain upkeep of the website, plus additional enhancements that benefit the league. $101 of the fees go to a prize pool.

The money comes out of either previous year winnings, any positive balance remaining from previous payments, or a payment made directly to NPL. Instructions on how to pay are communicated each year. Presently, payments are accepted only via PayPal (no fees from PayPal allowed, or send enough to cover fees), Venmo, and Square.

If an existing owner develops an unavoidable professional conflict of interest, the directors may choose to waive the portion of annual dues that contributes to the prize pool and declare that team exempt from prizes for the duration of the conflict of interest in lieu of that owner leaving the league.

### Timing

League fees can be paid at any point, but due by the end of October. This date ensures that we have active owners for each team leading into offseason that directly impacts the following regular season.

Should an owner not pay the league fee by the end of October and has not informed the league of their departure, the rosters of the unpaid teams will be frozen. What this means is that no action can be taken by the owner until he/she has paid: no trades, no transactions, nothing of the like—even if it means they miss the deadline to perform a transaction.

Additionally, unpaid teams are considered vacant and will be replaced without communication (and payment) from the owner. If a new owner is found, payment must be received first before they are announced to the league and can partake in any transactions.

### Winnings

The prize pool is broken down as such:

* Wild Card Losers(2): $50.00
* Wild Card Winners (2): $100.00
* Division Winners (6) $200.00
* Pennant Losers (2): $40.50
* Pennant Winners (2): $121.50
* World Series Winner (1): $600.00

This means the maximum an organization can win each year is $921.50: Division Winner, Pennant Winner, World Series Winner.

### Paying Out

Winnings are paid out to league fees first before being distributed via the medium of the league’s choosing. Meaning, each team will have their prior year’s winnings removed from their league fee balance first before pay out.

Any outstanding balance remaining on league fees after this is applied must be paid by the owner. Any overage (so anyone who made the Championship Series in each year) will be paid out to owners once all league fees have been paid in.

Owners have the ability to leave any winnings with the league and have it apply to future year payouts.