---
title: "nplrules"
---

## About

The National Pastime League (NPL) was founded in February 2015 by Evan Brunell (Defenestrations of Prague) and Gerald Andriole (former owner, MIT Beavers).

The current NPL directors are Jarrett Seidler (Asbury Park Bosses), Michael Sarinsky (Hunter Gatherers), Tommy Bennett (Los Angeles Bulldog), Chris Fargis (Brooklyn TOOTBLANs), Bret Sayre (Cheesequake Cheddar), and Daniel Rathman (Defenestrations of Prague).

Before founding NPL, Evan and Gerald were members of the Big Show League, part of Reality Fantasy Baseball. Big Show League was in operation for many years, with the most recent iteration born in 2006. Using RFB’s proprietary engine, Big Show was designed to mimic MLB as closely as possible for the most realistic fantasy baseball experience possible.

For several reasons, Evan and Gerald decided to create their own take on a fantasy baseball league modeled after actual mechanics of an MLB team and formed their own league. Many owners from Big Show are also members of NPL.

After one year using RFB’s proprietary engine, NPL shifted to the Scoresheet platform. Using real-life statistics of baseball players, fantasy statistics are generated with head-to-head games against other teams in the league. Adherence to MLB rules is prioritized and applied whenever possible.